/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentOrganizer;

import java.io.File;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ryan
 */
public class EditStudents extends javax.swing.JFrame {

    /**
     * Creates new form EditStudent
     */
    String firstName;
    String lastName;
    Student selectedStudent;

    ArrayList<Student> studentData;
    ArrayList<ClassGroup> classData;
    ArrayList<StudentGrade> gradeData;

    File classFile = new File("classFile.txt");
    File gradeFile = new File("gradeFile.txt");
    File studentFile = new File("studentFile.txt");

    SearchHelper searcher = new SearchHelper();
    WriterClass writer = new WriterClass();
    ReaderHelper reader = new ReaderHelper();

    DefaultListModel<String> extracurricularsModel = new DefaultListModel<>();
    DefaultListModel<String> allergiesModel = new DefaultListModel<>();

    public EditStudents(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;

        studentData = reader.readStudentInformation();
        classData = reader.readClassActivities();
        gradeData = reader.readStudentGrades();

        selectedStudent = searcher.findStudent(studentData, firstName, lastName);

        initComponents();

        currentStudentData();

        addClassesToYearCBox();
    }

    public EditStudents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        classLabel = new javax.swing.JLabel();
        dOBTextField = new javax.swing.JTextField();
        dOBLabel = new javax.swing.JLabel();
        contactTextField = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        leavingTextField = new javax.swing.JTextField();
        leavingLabel = new javax.swing.JLabel();
        extracurricularLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allergiesList = new javax.swing.JList<>();
        allergyLabel = new javax.swing.JLabel();
        extracurricularTextField = new javax.swing.JTextField();
        addECAButton = new javax.swing.JButton();
        removeECAButton = new javax.swing.JButton();
        allergyTextField = new javax.swing.JTextField();
        addAllergyButton = new javax.swing.JButton();
        removeAllergyButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        extracurricularsList = new javax.swing.JList<>();
        confirmChangesButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesTextArea = new javax.swing.JTextArea();
        notesLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        yearCBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Student");

        returnButton.setForeground(new java.awt.Color(244, 94, 89));
        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("First Name:");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        classLabel.setText("Year Level:");

        dOBTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dOBTextFieldActionPerformed(evt);
            }
        });

        dOBLabel.setText("DOB:");

        contactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTextFieldActionPerformed(evt);
            }
        });

        contactLabel.setText("Contact:");

        leavingTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavingTextFieldActionPerformed(evt);
            }
        });

        leavingLabel.setText("Leaving:");

        extracurricularLabel.setText("ECAs: ");

        allergiesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        allergiesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                allergiesListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(allergiesList);

        allergyLabel.setText("Allergies:");

        extracurricularTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extracurricularTextFieldActionPerformed(evt);
            }
        });

        addECAButton.setText("Add");
        addECAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addECAButtonActionPerformed(evt);
            }
        });

        removeECAButton.setText("Remove");
        removeECAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeECAButtonActionPerformed(evt);
            }
        });

        allergyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergyTextFieldActionPerformed(evt);
            }
        });

        addAllergyButton.setText("Add");
        addAllergyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAllergyButtonActionPerformed(evt);
            }
        });

        removeAllergyButton.setText("Remove");
        removeAllergyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllergyButtonActionPerformed(evt);
            }
        });

        extracurricularsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        extracurricularsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                extracurricularsListMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extracurricularsListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(extracurricularsList);

        confirmChangesButton.setForeground(new java.awt.Color(94, 244, 9));
        confirmChangesButton.setText("Confirm");
        confirmChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChangesButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        titleLabel.setText("Edit Selected Student");

        notesTextArea.setColumns(20);
        notesTextArea.setRows(5);
        jScrollPane2.setViewportView(notesTextArea);

        notesLabel.setText("Notes:");

        lastNameLabel.setText("Last Name:");

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        deleteButton.setForeground(new java.awt.Color(253, 51, 8));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        yearCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(allergyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allergyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addAllergyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                            .addComponent(confirmChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(removeAllergyButton)
                                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(contactLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dOBLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(classLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(leavingLabel)
                                    .addComponent(extracurricularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leavingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(extracurricularTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addECAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(removeECAButton))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notesLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(222, 222, 222)))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(returnButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classLabel)
                            .addComponent(yearCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dOBLabel)
                            .addComponent(dOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactLabel)
                            .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leavingLabel)
                            .addComponent(leavingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extracurricularTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extracurricularLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeECAButton)
                            .addComponent(addECAButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allergyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allergyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAllergyButton)
                            .addComponent(removeAllergyButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(660, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // method to handle returnButton pressed
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // create and show ViewStudents frame 
        ViewStudent viewStudent = new ViewStudent(firstName, lastName);
        viewStudent.show();
        // current frame closed 
        dispose();

    }//GEN-LAST:event_returnButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void dOBTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dOBTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dOBTextFieldActionPerformed

    private void contactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTextFieldActionPerformed

    private void leavingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavingTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leavingTextFieldActionPerformed

    private void extracurricularTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extracurricularTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extracurricularTextFieldActionPerformed

    private void allergyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergyTextFieldActionPerformed

    
    // method to handle confirmChangesButton pressed
    private void confirmChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmChangesButtonActionPerformed
        // get all user inputs from TextField and store in variable 
        // all leading/trailing spaces are removed with .trim()
        String firstName = firstNameTextField.getText().trim();
        String lastName = lastNameTextField.getText().trim();
        String yearLevel = yearCBox.getSelectedItem().toString().trim();
        String dateOfBirth = dOBTextField.getText().trim();
        String parentalContact = contactTextField.getText().trim();
        String leavingMethod = leavingTextField.getText().trim();
        String notes = notesTextArea.getText().trim();
        // get extracurriculars and allergies using return methods
        ArrayList<String> extracurriculars = returnExtracurriculars();
        ArrayList<String> allergies = returnAllergies();

        // Checks if notes are empty
        if (notes.trim().isEmpty()) {
            // if yes, set to "none"
            notes = "none";
        }

        // function to check if inputted fields are valid
        // returns true if valid, false if not 
        boolean flag = checkIfFieldsValid(firstName, lastName, dateOfBirth, parentalContact, leavingMethod);

        // editted student only created if all fields are valid/flag is true:
        if (flag) {
            // all spaces in notes replaced with _ to store as one string
            notes = notes.replace(" ", "_");
            // student created 
            // all details inputted, obsucred due to length of constructor
            Student edittedStudent = new Student(firstName, lastName, yearLevel, dateOfBirth, parentalContact, leavingMethod, notes, extracurriculars, allergies);
            
            // find currentStudent 
            selectedStudent = searcher.findStudent(studentData, selectedStudent.getFirstName(), selectedStudent.getLastName());

            // edtited student info is added and stored
            studentData.add(edittedStudent);
            // current student info is removed 
            studentData.remove(selectedStudent);
            
            // save studentData ArrayList using apporpriate writer method
            try {
                writer.saveStudentInformation(studentData);
            } catch (Exception e) {
                System.out.println("error");
            }

            // if student year level is changed, grades must be updated - a 'blank' copy is created for the new class's activities. 
            if (!selectedStudent.getYearLevel().equals(yearLevel)) {
                // update their grades 
                updateStudentActivities(firstName, lastName, yearLevel);

            // if first/last name is changed, student grade must be updated with new name(s), but keep same grades. 
            } else if (!selectedStudent.getFirstName().equals(firstName) || !selectedStudent.getLastName().equals(lastName)) {
                // update their grade names 
                updateGradeName(firstName, lastName);

            }
            
            // create and show ViewStudent frame 
            ViewStudent viewStudent = new ViewStudent(firstName, lastName);
            viewStudent.show();
            // current frame closed 
            dispose();

        }

    }//GEN-LAST:event_confirmChangesButtonActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void extracurricularsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extracurricularsListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_extracurricularsListMouseClicked

    private void extracurricularsListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extracurricularsListMousePressed
        String selected = extracurricularsList.getSelectedValue();

        extracurricularTextField.setText(selected);
    }//GEN-LAST:event_extracurricularsListMousePressed

    private void allergiesListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allergiesListMousePressed
        String selected = allergiesList.getSelectedValue();

        allergyTextField.setText(selected);
    }//GEN-LAST:event_allergiesListMousePressed

    private void addECAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addECAButtonActionPerformed
       // get user inputted text from extracurricular TextField
        String extracurricular = extracurricularTextField.getText();

        // check if extracurricular is blank 
        if (!extracurricular.isEmpty()) {
            // if not, add extracurricular to JList model (extracurricularsModel)
            extracurricularsModel.addElement(extracurricular);
            // update model
            extracurricularsList.setModel(extracurricularsModel);
        } else {
            // if blank, output appropriate error message
            JOptionPane.showMessageDialog(null, "Error: Extracurricular activity cannot be blank.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        // reset TextField to blank 
        extracurricularTextField.setText("");
    }//GEN-LAST:event_addECAButtonActionPerformed

    private void removeECAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeECAButtonActionPerformed
        // get user inputted text from extracurricular TextField
        String selectedExtracurricular = extracurricularTextField.getText().toLowerCase();

        // loop through each item currently in extracurriculars JList model
        for (int i = 0; i < extracurricularsModel.getSize(); i++) {
            // get current item 
            String currentExtracurricular = extracurricularsModel.getElementAt(i).toLowerCase();

            // check if user inputted extracurricular matches current item
            if (currentExtracurricular.equals(selectedExtracurricular)) {
                // if yes, remove element from extracurriculars JList model
                extracurricularsModel.removeElementAt(i);

                // update model
                extracurricularsList.setModel(extracurricularsModel);
            } 
        }
        // reset TextField to blank
        extracurricularTextField.setText("");
    }//GEN-LAST:event_removeECAButtonActionPerformed

    private void addAllergyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllergyButtonActionPerformed
        String allergy = allergyTextField.getText();

        if (!allergy.isEmpty()) {
            allergiesModel.addElement(allergy);
            allergiesList.setModel(allergiesModel);
            allergyTextField.setText("");
        } else {

            // if blank, output appropriate error message
            JOptionPane.showMessageDialog(null, "Error: Allergy cannot be blank.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addAllergyButtonActionPerformed

    private void removeAllergyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllergyButtonActionPerformed
         String selectedAllergy = allergyTextField.getText().toLowerCase();

        for (int i = 0; i < allergiesModel.getSize(); i++) {
            String currentAllergy = allergiesModel.getElementAt(i).toLowerCase();

            if (currentAllergy.equals(selectedAllergy)) {
                allergiesModel.removeElementAt(i);
                allergyTextField.setText("");
            } else {

                // if allergy doesn't exist, output appropriate error message: 
                JOptionPane.showMessageDialog(null, "Error: No such allergy exists.", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }

        allergiesList.setModel(allergiesModel);
    }//GEN-LAST:event_removeAllergyButtonActionPerformed

    // method to handle deleteButton pressed
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // remove selected student from studentData ArrayList
        studentData.remove(selectedStudent);
        // save updated ArrayList using appropriate writer method
        try {
            writer.saveStudentInformation(studentData);
        } catch (Exception e) {
            System.out.println("error");
        }
        // find selected student's grades 
        StudentGrade selectedGrades = searcher.findGrade(gradeData, selectedStudent.getFirstName(), selectedStudent.getLastName());
        // remove selected student's grades from ArrayList
        gradeData.remove(selectedGrades);
        // save updated ArrayList using appropriate writer method
        try {
            writer.saveGradeInformation(gradeData);
        } catch (Exception e) {
            System.out.println("error");
        }
        // create and show MainWindow frame
        MainWindow mainWindow = new MainWindow();
        mainWindow.show();
        // current frame closed 
        dispose();

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void yearCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearCBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudents().setVisible(true);
            }
        });
    }

    private void currentStudentData() {
        firstNameTextField.setText(selectedStudent.getFirstName());
        lastNameTextField.setText(selectedStudent.getLastName());
        dOBTextField.setText(selectedStudent.getDateOfBirth());
        contactTextField.setText(selectedStudent.getParentalContact());
        leavingTextField.setText(selectedStudent.getLeavingMethod());
        notesTextArea.setText(selectedStudent.getNotes().replace("_", " "));

        extracurricularTextField.setText("");
        allergyTextField.setText("");

        ArrayList<String> extracurriculars = selectedStudent.getExtracurriculars();
        ArrayList<String> allergies = selectedStudent.getAllergies();

        for (String activity : extracurriculars) {
            // Removing any _ joining words so it's easier to see for the user
            activity = activity.replaceAll("_", " ");
            extracurricularsModel.addElement(activity);
        }

        extracurricularsList.setModel(extracurricularsModel);

        for (String allergy : allergies) {
            // Removing any _ joining words so it's easier to see for the user
            allergy = allergy.replaceAll("_", " ");
            allergiesModel.addElement(allergy);
        }

        allergiesList.setModel(allergiesModel);
    }

    // method to create a ArrayList of "N/A" grades for a new student's class activities
    public ArrayList<String> blankStudentGrades(ClassGroup classGroup) {
        // new ArrayList created
        ArrayList<String> newGrades = new ArrayList<>();

        // for each activity in ClassGroup
        for (String activity : classGroup.getActivities()) {
            // add N/A to ArrayList
            newGrades.add("N/A");
        }

        // ArrayList is returned
        return newGrades;
    }
    
    // method to fill yearCBox with names of current classes
    public void addClassesToYearCBox() {
        
        // if there are ClassGroups in classData
        if (!classData.isEmpty()) {
            // for each ClassGroup
            for (int i = 0; i < classData.size(); i++) {
                // get their name attribute
                // add to yearCBox
                yearCBox.addItem(classData.get(i).getClassName());
                
            }
            // remove default yearCBox item, "none"
            yearCBox.removeItem("None");

        }
    }

    public ArrayList<String> returnExtracurriculars() {
        ArrayList<String> extracurriculars = new ArrayList<>();
        // Inputs all extracurricars from its jList model into an array

        if (extracurricularsModel.getSize() != 0) {
            for (int i = 0; i < extracurricularsModel.getSize(); i++) {
                // when inputting, spaces between words must be replaced with _ to be one string
                // leading/trailing spaces are NOT replaced with _

                // removing leading/trailing spaces:
                String extracurricular = extracurricularsModel.getElementAt(i).trim();

                // remaining spaces between words are replaced with _:
                extracurricular = extracurricular.replaceAll("\\s", "_");

                extracurriculars.add(extracurricular);
            }

            // If the model is empty, none is inputted instead:
        } else {
            extracurriculars.add("none");
        }

        return extracurriculars;
    }

    public ArrayList<String> returnAllergies() {
        ArrayList<String> allergies = new ArrayList<>();
        // Inputs all allergies from its jList model into an array
        // If the model is empty, none is inputted instead

        if (allergiesModel.getSize() != 0) {
            for (int i = 0; i < allergiesModel.getSize(); i++) {
                // When inputting, spaces between words must be replaced with _ to be one string
                // Leading/trailing spaces are NOT replaced with _

                // Removing leading/trailing spaces:
                String allergy = allergiesModel.getElementAt(i).trim();

                // Remaining spaces between words are replaced with _:
                allergy = allergy.replaceAll("\\s", "_");

                allergies.add(allergy);
            }

            // If the model is empty, none is inputted instead:       
        } else {
            allergies.add("none");
        }

        return allergies;
    }

    public boolean checkIfFieldsValid(String firstName, String lastName, String dateOfBirth, String parentalContact, String leavingMethod) {

        boolean flag = true;

        String dateRegex = "(0[1-9]||[12][0-9]||3[01])/(0[1-9]||1[0-2])/\\d{4}"; // regular expression to match date

        Pattern datePattern = Pattern.compile(dateRegex);
        Matcher dateMatch = datePattern.matcher(dateOfBirth);

        // Flag returns as false if any of the fields are not valid
        // Check if required fields are empty:
        if (firstName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: The first name is not inputted.", "Error", JOptionPane.ERROR_MESSAGE);
            flag = false;

        } else if (lastName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: The last name is not inputted.", "Error", JOptionPane.ERROR_MESSAGE);
            flag = false;

        } else if (parentalContact.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: Parental contact is not inputted.", "Error", JOptionPane.ERROR_MESSAGE);
            flag = false;

            // check if there are unwanted spaces between characters in fields
        } else if (firstName.contains(" ")) {
            // if yes, output first name incorrect input error message
            JOptionPane.showMessageDialog(null, "Error: First name not inputted correctly.", "Error", JOptionPane.ERROR_MESSAGE);
            flag = false;

        } else if (lastName.contains(" ")) {
            // if yes, output last name incorrect input error message
            JOptionPane.showMessageDialog(null, "Error: Last name not inputted correctly.", "Error", JOptionPane.ERROR_MESSAGE);
            flag = false;

        } else if (parentalContact.contains(" ")) {
            // if yes, output parental contact incorrect input error message
            JOptionPane.showMessageDialog(null, "Error: Parental contact not inputted correctly.", "Error", JOptionPane.ERROR_MESSAGE);
            flag = false;

        } else if (leavingMethod.contains(" ")) {
            // if yes, output leaving method incorrect input error message
            JOptionPane.showMessageDialog(null, "Error: Leaving method not inputted correctly.", "Error", JOptionPane.ERROR_MESSAGE);
            flag = false;

            // Check if date is inputted correctly and is valid:
        } else if (dateMatch.matches() != true) {
            JOptionPane.showMessageDialog(null, "Error: Birthday must be in DD/MM/YYYY format and a valid date.", "Error", JOptionPane.ERROR_MESSAGE);
            flag = false;

        }
        return flag;
    }
    
    // method to update student grade name 
    public void updateGradeName(String firstName, String lastName) {
        // retrieve student grade object to be editted
        StudentGrade studentGrade = searcher.findGrade(gradeData, selectedStudent.getFirstName(), selectedStudent.getLastName());

        // first name and/or last name is changed:
        studentGrade.setFirstName(firstName);
        studentGrade.setLastName(lastName);

        // grade data is saved using appropriate writer method 
        try {
            writer.saveGradeInformation(gradeData);
        } catch (Exception e) {
            System.out.println("error");
        }

    }
    
    // method to update grade activities
    public void updateStudentActivities(String firstName, String lastName, String yearLevel) {
        // retrieve classgroup of student for activities
        ClassGroup classGroup = searcher.findClass(classData, yearLevel);
        // create 'n/a' template for grades
        ArrayList<String> newGrades = blankStudentGrades(classGroup);
        // create a new StudentGrade with ArrayList
        StudentGrade newGrade = new StudentGrade(firstName, lastName, newGrades);
        StudentGrade oldGrade = searcher.findGrade(gradeData, selectedStudent.getFirstName(), selectedStudent.getLastName());

        // current student grade is removed, updated is added:
        gradeData.add(newGrade);
        gradeData.remove(oldGrade);

        // grade data is saved using appropriate writer method:
        try {
            writer.saveGradeInformation(gradeData);
        } catch (Exception e) {
            System.out.println("error");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAllergyButton;
    private javax.swing.JButton addECAButton;
    private javax.swing.JList<String> allergiesList;
    private javax.swing.JLabel allergyLabel;
    private javax.swing.JTextField allergyTextField;
    private javax.swing.JLabel classLabel;
    private javax.swing.JButton confirmChangesButton;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JLabel dOBLabel;
    private javax.swing.JTextField dOBTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel extracurricularLabel;
    private javax.swing.JTextField extracurricularTextField;
    private javax.swing.JList<String> extracurricularsList;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel leavingLabel;
    private javax.swing.JTextField leavingTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JTextArea notesTextArea;
    private javax.swing.JButton removeAllergyButton;
    private javax.swing.JButton removeECAButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> yearCBox;
    // End of variables declaration//GEN-END:variables
}
